#ifndef GLOBAL_CONSTANTS_H
#define GLOBAL_CONSTANTS_H

const double ENGINE_TIMESTEP = 1.0/60.0;

const int WINDOW_WIDTH = 640;
const int WINDOW_HEIGHT = 480;

const int STAIRCASE_STEPSIZE = -6;

#endif // GLOBAL_CONSTANTS_H
